#cloudbuild.yaml
steps:

# Build and tag pygdal image
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'europe-west6-docker.pkg.dev/$PROJECT_ID/ohd-repo/pygdal:$SHORT_SHA'
  - '-t'
  - 'europe-west6-docker.pkg.dev/$PROJECT_ID/ohd-repo/pygdal:latest'
  - '.'

# Store the image in Container Registry
images:
  - 'europe-west6-docker.pkg.dev/$PROJECT_ID/ohd-repo/pygdal:$SHORT_SHA'
  - 'europe-west6-docker.pkg.dev/$PROJECT_ID/ohd-repo/pygdal:latest'

timeout: 1500s