#cloudbuild.yaml
steps:

# Build and tag pygdal image
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/pygdal:$SHORT_SHA'
  - '-t'
  - 'gcr.io/$PROJECT_ID/pygdal:latest'

# Store the image in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/pygdal:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/pygdal:latest'

timeout: 1500s